front_homepage:
    path:     /
    defaults: { _controller: FrontBundle:Front:index }

list_enquette_type:
    path:     /enquette/{theme}
    defaults: { _controller: FrontBundle:Front:listEnquete }
