user:
    resource: "@UserBundle/Resources/config/routing.yml"
    
backend:
    resource: "@BackendBundle/Resources/config/routing.yml"
    prefix:   /backend

front:
    resource: "@FrontBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group    

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin